name: Deploy para Hostnet via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Enviar arquivos para a Hostnet via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/
          exclude: |
          **/.git*
          **/.git*/**
          .github/**
          README.md
